# Generated by Django 4.2.11 on 2024-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
